In [11]:
import pandas as pd
import os
from pathlib import Path
import sys
import time
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import meteostat
from tqdm import tqdm
import pickle

In [12]:
df_world_cities = pd.read_csv('/home/kieran/Documents/Datasets/Global streetscapes/global-streetscapes/code/raw_download/data/worldcities.csv')

In [13]:
df_world_cities.dropna(subset=['city_ascii','lat','lng'])

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6839,139.7744,Japan,JP,JPN,Tōkyō,primary,39105000.0,1392685764
1,Jakarta,Jakarta,-6.2146,106.8451,Indonesia,ID,IDN,Jakarta,primary,35362000.0,1360771077
2,Delhi,Delhi,28.6667,77.2167,India,IN,IND,Delhi,admin,31870000.0,1356872604
3,Manila,Manila,14.6000,120.9833,Philippines,PH,PHL,Manila,primary,23971000.0,1608618140
4,São Paulo,Sao Paulo,-23.5504,-46.6339,Brazil,BR,BRA,São Paulo,admin,22495000.0,1076532519
...,...,...,...,...,...,...,...,...,...,...,...
42900,Tukchi,Tukchi,57.3670,139.5000,Russia,RU,RUS,Khabarovskiy Kray,NaN,10.0,1643472801
42901,Numto,Numto,63.6667,71.3333,Russia,RU,RUS,Khanty-Mansiyskiy Avtonomnyy Okrug-Yugra,NaN,10.0,1643985006
42902,Nord,Nord,81.7166,-17.8000,Greenland,GL,GRL,Sermersooq,NaN,10.0,1304217709
42903,Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
42904,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468

In [14]:
city_lat = df_world_cities['lat'].iloc[0]
city_lon = df_world_cities['lng'].iloc[0]

In [16]:
start = datetime(2018,1,1) #TODO: Make arbitrary (for all time?)
end = datetime(2025,1,1)
print(type(city_lat))
print(type(city_lon))
print(type(start))
print(type(end))
city_point = meteostat.Point(city_lat,city_lon,0)
city_point.alt_range = 2000#2km alt range to be generous
data = meteostat.Daily(city_point,start,end)
data.fetch()

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'datetime.datetime'>
<class 'datetime.datetime'>

            tavg  tmin  tmax  prcp  snow  wdir  wspd  wpgt    pres  tsun
time
2018-01-01   7.2   0.4  13.0   0.0  <NA>  <NA>   9.5  <NA>  1012.6  <NA>
2018-01-02   5.9   0.8  10.8   0.0  <NA>  <NA>  11.8  <NA>  1014.4  <NA>
2018-01-03   4.3   2.9   8.6   0.0  <NA>  <NA>  18.7  <NA>  1013.0  <NA>
2018-01-04   4.9   0.0   9.6   0.0  <NA>  <NA>  10.1  <NA>  1018.0  <NA>
2018-01-05   2.9   1.7   6.3   0.0  <NA>  <NA>   6.7  <NA>  1015.6  <NA>
...          ...   ...   ...   ...   ...   ...   ...   ...     ...   ...
2024-12-28   5.4   1.9  10.5   0.0  <NA>  <NA>   6.1  <NA>  1010.9  <NA>
2024-12-29   6.0   0.9  11.3   0.0  <NA>  <NA>   6.6  <NA>  1016.1  <NA>
2024-12-30   6.2   3.9   9.6   0.0  <NA>  <NA>   7.0  <NA>  1020.4  <NA>
2024-12-31   8.0   3.0  13.8   0.0  <NA>  <NA>   7.4  <NA>  1006.6  <NA>
2025-01-01   8.2   4.8  11.4   0.0  <NA>  <NA>   8.5  <NA>  1016.2  <NA>

[2558 rows x 10 columns]